apiVersion: v2
name: api-operator-istio
description: A helm chart to deploy the api operator for istio

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1
# version: 1.1.1 - Templatized hardcoded images
# version: 1.1.0 - updated to use v1 of CRD spec
# version: 1.0.4 - added job to avoid istio-ingress to patch as Loadbalancer if present in any other type
# version: 1.0.3 - minor bugfixes
# version: 1.0.2 - removed operator-command configMap - no longer using entrypoint.sh
# version: 1.0.1 - minor fixes
# version: 1.0.0 - initial version

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1"
