apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "componentvaults.oda.tmforum.org"
spec:
  group: "oda.tmforum.org"
  scope: "Namespaced"
  names:
    plural: "componentvaults"
    singular: "componentvault"
    shortNames: ["compvault", "compvaults"]
    kind: "ComponentVault"
  versions:
  - name: "v1beta3"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    deprecated: false
    # This overrides the default warning returned to API clients making v1alpha1 API requests.
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            required: ["type", "podSelector"]
            properties:
              type:
                type: string
                enum: ["sideCar"]
                description: defines, how Components access the Secrets, currently only sideCar is supported
              sideCar:
                type: object
                description: sideCar parameters, required if type has value "sideCar"
                required: ["port"]
                properties:
                  port:
                    type: integer
                    description: The port where the API is exposed in the sideCar (localhost:<port>)
              podSelector:
                type: object
                description: defines, which PODs are allowed to access the secrets (and logic)
                properties:
                  namespace:
                    type: string
                    description: glob patter matching the namespace of the POD
                  name:
                    type: string
                    description: glob patter matching the name of the POD
                  serviceaccount:
                    type: string
                    description: glob patter matching the serviceaccount od the POD
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              implementation:
                type: object
                properties:
                  ready:
                    type: boolean
    additionalPrinterColumns:
    - name: NAME_SEL
      type: string
      description: ComponentVault pod name selector
      jsonPath: .spec.podSelector.name
    - name: NAMESPACE_SEL
      type: string
      description: ComponentVault pod namespace selector
      jsonPath: .spec.podSelector.namespace
    - name: SVCACCT_SEL
      type: string
      description: ComponentVault pod serviceaccount selector
      jsonPath: .spec.podSelector.serviceaccount
    - name: READY
      type: string
      description: Component Vault configuration is ready
      jsonPath: .status.implementation.ready