apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depapi-op
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-depapi-op
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-depapi-op
    spec:
      serviceAccountName: {{ .Release.Name }}-depapi-op-account
      containers:
      - name: {{ .Release.Name }}-depapi-op
        image: {{ include "dependentapi-simple-operator.dockerimage" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: LOGGING
          value: "{{ .Values.loglevel }}"
        ports:
        - containerPort: 9443
