apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depapi-op
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-depapi-op
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-depapi-op
    spec:
      serviceAccountName: {{ .Release.Name }}-depapi-op-account
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "image-pull-secrets" . |nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-depapi-op
        image: {{ include "dependentapi-simple-operator.dockerimage" . }}
        imagePullPolicy: {{ include "dependentapi-simple-operator.imagePullPolicy" . }}
        env:
        - name: LOGGING
          value: "{{ .Values.loglevel }}"
        - name: COMPONENT_REGISTRY_URL
          value: "{{ .Values.componentRegistryUrl }}"
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.oauth2TokenSecret }}
              key: client_id
              optional: true
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.oauth2TokenSecret }}
              key: client_secret
              optional: true
        - name: OAUTH2_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.oauth2TokenSecret }}
              key: token_url
              optional: true
        ports:
        - containerPort: 9443
