{{ if .Values.serviceInventoryAPI.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-info-service
  labels:
    app: {{ .Release.Name }}-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-info-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-info-service
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "image-pull-secrets" . |nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}-info-service
        image: {{ include "dependentapi-serviceinventoryapi.dockerimage" . }}
        imagePullPolicy: {{ include "dependentapi-serviceinventoryapi.imagePullPolicy" . }}
        env:
        - name: SERVER_URL
          value: {{ .Values.serviceInventoryAPI.serverUrl }}
        ports:
        - containerPort: 8638
{{- end }}
