apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pdb-management-serving-cert
  namespace: canvas
spec:
  dnsNames:
  - pdb-management-webhook-service.canvas.svc
  - pdb-management-webhook-service.canvas.svc.cluster.local
  secretName: webhook-server-cert
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: pdb-management-selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pdb-management-selfsigned-issuer
spec:
  selfSigned: {} 