apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pdb-management
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
  name: pdb-management-leader-election-rolebinding
  namespace: canvas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pdb-management-leader-election-role
subjects:
- kind: ServiceAccount
  name: pdb-management-operator
  namespace: canvas
