apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pdb-management
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
  name: pdb-management-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pdb-management-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: pdb-management-operator
  namespace: canvas
