apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pdb-management
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
  name: pdb-management-operator
  namespace: canvas
