apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/name: pdb-management-mcp-service
    app.kubernetes.io/part-of: pdb-management
    app.kubernetes.io/managed-by: kustomize
  name: pdb-management-mcp-service
  namespace: canvas
spec:
  ports:
  - name: mcp
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: mcp-health
    port: 8091
    protocol: TCP
    targetPort: 8090
  selector:
    control-plane: pdb-management-operator
  type: ClusterIP