apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-webhook 
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "oda-webhook.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversion-webhook 
  template:
    metadata:
      labels:
        app: conversion-webhook 
        {{- include "oda-webhook.labels" . | nindent 8 }}
    spec:
      containers:
      - name: conversion-webhook 
        image: {{ include "oda-webhook.dockerimage" . }}
        imagePullPolicy: {{ include "oda-webhook.imagePullPolicy" .	 }}
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
      volumes:
        - name: secret-volume
          secret:
            secretName: compcrdwebhook-secret

