{{- if include "component-registry.read-source-token-secret" .  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauth2.tokenSecretName }}
type: Opaque
data:
  client_id: {{ .Release.STORE_oauth2SourceSecretData.client_id | quote }}
  client_secret: {{ .Release.STORE_oauth2SourceSecretData.client_secret | quote }}
  token_url: {{ .Release.STORE_oauth2SourceSecretData.token_url | quote }}
{{- end }}