apiVersion: v1
kind: Secret
metadata:
  name: {{ include "component-registry.secretname" . }}
type: Opaque
data:
  oauth2SecretKey: {{ include "component-registry.oauth2-secret-key" . | quote }}
  kcClientID: # { { include "component-registry.kc-client-id" . | quote } }
  kcClientSecret: # { { include "component-registry.kc-client-secret" . | quote } }
