deployment:
  controllerName: oda-controller-ingress
  compconImage: tmforumodacanvas/component-istio-controller:0.5.0
  compconImagePullPolicy: IfNotPresent
  istioGateway: true
  secconImage: tmforumodacanvas/security-listener:0.6.0
  monitoredNamespaces: 'components'           # comma separated list of namespaces
  ingressClass:
    enabled: false
    name: nginx
  dataDog:
    enabled: false
  keycloak:
    port: 8080
#We reuse the admin user created on keycloak instalation
credentials:
  user: admin
  pass: adpass
configmap:
  #kcbase: http://canvas-keycloak:8088/auth # trying to parameterise this in the configmap
  kcrealm: myrealm
  loglevel: '20'
