deployment:
  controllerName: oda-controller
  #compconImage: tmforumodacanvas/component-istio-controller:0.5.0
  compconImage: ocfork/component-istio-controller
  compconVersion: 0.4.2
  compconPrereleaseSuffix: odaa-98
  compconImagePullPolicy: IfNotPresent
  istioGateway: true
  #secconImage: tmforumodacanvas/security-listener:0.6.0
  # TODO: replace with tmforumodacanvas repo.  
  secconImage: ocfork/security-listener
  secconVersion: 0.7.0
  secconPrereleaseSuffix: odaa-98
  secconImagePullPolicy: IfNotPresent
  monitoredNamespaces: 'components'           # comma separated list of namespaces
  ingressClass:
    enabled: false
    name: nginx
  dataDog:
    enabled: false
  keycloak:
    port: 8080
#We reuse the admin user created on keycloak instalation
credentials:
  user: admin
  pass: adpass
configmap:
  #kcbase: http://canvas-keycloak:8088/auth # trying to parameterise this in the configmap
  kcrealm: myrealm
  loglevel: '20'
