apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  namespace: kong
spec:
  replicas: {{ .Values.kongoperatorreplicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
      - name: {{ .Release.Name }}-operator
        image: {{ .Values.kongoperatorimage.repository }}
        imagePullPolicy: {{ .Values.kongoperatorimage.pullPolicy }}