
kcUsername: admin
## plain text admin password. If not set the k8s secret canvasKeycloakSecret[adminPasswordKey] will be used
# kcPassword: "****"
canvasKeycloakSecret: canvas-keycloak
adminPasswordKey: admin-password

kcAdminClientID: canvassystem
kcAdminClientSecret:

# kcBaseUrl: https://canvas-keycloak.ihc-dt.cluster-2.de/auth
kcBaseUrl: http://canvas-keycloak.canvas.svc.cluster.local:8083/auth
kcRealm: odari
compregAdminInitPassword: 
compregViewerInitPassword: 

