openapi: 3.0.3
info:
  title: Component Vault - OpenAPI 3.0
  description: |-
    "This is a simple key-value store
    Some useful links:
    - [The sources](https://github.com/.../openapi.yaml)"
  termsOfService: http://.../
  contact:
    email: ferenc.hechler@telekom.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: Find out more about Component Vault
  url: http://.../
servers:
- url: http://localhost:5000/api/v3/
tags:
- name: secret
  description: Secure Key-Value store
  externalDocs:
    description: Find out more
    url: http://...
paths:
  /secret:
    post:
      tags:
      - secret
      summary: Create secret
      description: auth needed.
      operationId: createSecret
      requestBody:
        description: Created secret object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Secret'
          application/xml:
            schema:
              $ref: '#/components/schemas/Secret'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Secret'
      responses:
        "201":
          description: Successful created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Secret'
            application/xml:
              schema:
                $ref: '#/components/schemas/Secret'
        default:
          description: Unexpected error
  /secret/{secretKey}:
    get:
      tags:
      - secret
      summary: Get secret by secretKey
      description: ""
      operationId: getSecretByKey
      parameters:
      - name: secretKey
        in: path
        description: 'The key of the secret. '
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Secret'
            application/xml:
              schema:
                $ref: '#/components/schemas/Secret'
        default:
          description: Unexpected error
    put:
      tags:
      - secret
      summary: Update secret
      description: auth needed.
      operationId: updateSecret
      parameters:
      - name: secretKey
        in: path
        description: key that need to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Update an existent secret in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Secret'
          application/xml:
            schema:
              $ref: '#/components/schemas/Secret'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Secret'
      responses:
        "201":
          description: Successful created
        "204":
          description: Successful updated
        default:
          description: Unexpected error
    delete:
      tags:
      - secret
      summary: Delete secret
      description: auth needed
      operationId: deleteSecret
      parameters:
      - name: secretKey
        in: path
        description: The key that needs to be deleted
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Successful deleted
        default:
          description: Unexpected error
components:
  schemas:
    Secret:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      example:
        key: db-password
        value: H37c5bza+d9.de89
      xml:
        name: secret
  requestBodies:
    Secret:
      description: Secret object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Secret'
        application/xml:
          schema:
            $ref: '#/components/schemas/Secret'
  securitySchemes:
    componentvault_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://componentvault.ihc-dt.cluster-3.de/oauth/authorize
          scopes:
            write:secret: modify secrets in your account
            read:secret: read your secrets
    api_key:
      type: apiKey
      name: api_key
      in: header
