{{ if .Values.canvasResourceInventory }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "component-registry.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "component-registry.serviceAccountName" . }}-cluster-role
rules:

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [oda.tmforum.org]
    resources: [components, exposedapis]
    verbs: [list, watch, get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "component-registry.serviceAccountName" . }}-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "component-registry.serviceAccountName" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "component-registry.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
{{ end }}