apiVersion: v1
kind: Service
metadata:
  name: resource-inventory  
          # do not use {{ .Release.Name }}-resource-inventory, 
          # because the service has to be accessible under the 
        
          # fixed endpoint resource-inventory.canvas.svc.cluster.local
  labels:
    app: {{ .Release.Name }}-resource-inventory
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8639
  selector:
    app: {{ .Release.Name }}-resource-inventory