apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-digitalidentityapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-digitalidentityapi
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-digitalidentityapi
        version: reference-digitalidentityapi-latest
    spec:
      containers:
      - name: {{.Release.Name}}-digitalidentityapi
        image: localhost:5000/tmf720_digital-identity-management_v4.0.0:batch
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}           
        imagePullPolicy: Always
        ports:
        - name: {{.Release.Name}}-diapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/digitalIdentityManagement/v4/digitalIdentity
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5          
          failureThreshold: 30 
         
